### ISSUE TITLE
Some videos will not play anymore

### ISSUE THREAD

**Issue by Invictaz** [andoma/movian-plugin-youtube#9]
Video https://www.youtube.com/watch?v=RHdC9PfTITo

Does not play. Plugin version 5.0.12

Movian 5.0.507

-----------
04:29:32.872: HTTP-872        [DEBUG]:Chunked transfer
04:29:32.880: HTTP            [DEBUG]:Parking connection to www.youtube.com:443 (cid=779) (expire in 5s) -- Request destroyed
04:29:32.882: THREADS         [DEBUG]:Created thread estimer (0x11000a0)
04:29:32.895: youtube         [ERROR]:TypeError (undefined not callable) at ytdl-core/lib/sig:26
04:29:32.895: youtube         [ERROR]:STACK DUMP: TypeError: undefined not callable
04:29:32.895:                             at [anon] (duk_js_call.c:770) internal
04:29:32.896:                             at [anon] (ytdl-core/lib/sig:26)
04:29:32.896:                             at [anon] (ytdl-core/lib/info:196)
04:29:32.897:                             at [anon] (ytdl-core/lib/request:43)
04:29:32.897:                             at [anon] (http:14) preventsyield
04:29:32.898: youtube         [ERROR]:Native callsite timer_thread() at /project/repo/checkout/src/ecmascript/es_timer.c:148
04:29:32.898: THREADS         [DEBUG]:Thread 0x11000a0 (estimer) exiting

**Comment by Invictaz** [comment]
I tried to fix it by replacing the files in ytdl-core with newer ones as Buksa said ytdl-core was updated but that did not fix the issue.

[youtube.zip](https://github.com/andoma/movian-plugin-youtube/files/1817414/youtube.zip)

**Comment by wdshrk** [comment]
Hello. 
Created a pull request with possible issue fix.

BR

**Comment by Invictaz** [comment]
@wdshrk indeed fixes it.
